@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 05 07:15:55 +0545 2025
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_topmodule_behav -key {Behavioral:sim_1:Functional:tb_topmodule} -tclbatch tb_topmodule.tcl -view G:/fpga_lab/8bit-RSIC-Processor/tb_topmodule_behav_1.wcfg -log simulate.log"
call xsim  tb_topmodule_behav -key {Behavioral:sim_1:Functional:tb_topmodule} -tclbatch tb_topmodule.tcl -view G:/fpga_lab/8bit-RSIC-Processor/tb_topmodule_behav_1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
